// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNCcil3kyW-PZXJGvPE1YCq4nfEtGlREo',
    appId: '1:240127573028:web:57388974ce9f2492f66cb1',
    messagingSenderId: '240127573028',
    projectId: 'ite-e3-todoapp',
    authDomain: 'ite-e3-todoapp.firebaseapp.com',
    storageBucket: 'ite-e3-todoapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVvpJ-lv8E1KliISWu6elrmM17cgSirvI',
    appId: '1:240127573028:android:a80500470d92134af66cb1',
    messagingSenderId: '240127573028',
    projectId: 'ite-e3-todoapp',
    storageBucket: 'ite-e3-todoapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ1KI7YwUmcoD9nrMJPLbozheUNvkBpTI',
    appId: '1:240127573028:ios:b262ac0c96345b90f66cb1',
    messagingSenderId: '240127573028',
    projectId: 'ite-e3-todoapp',
    storageBucket: 'ite-e3-todoapp.firebasestorage.app',
    iosBundleId: 'com.example.mytaskProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ1KI7YwUmcoD9nrMJPLbozheUNvkBpTI',
    appId: '1:240127573028:ios:b262ac0c96345b90f66cb1',
    messagingSenderId: '240127573028',
    projectId: 'ite-e3-todoapp',
    storageBucket: 'ite-e3-todoapp.firebasestorage.app',
    iosBundleId: 'com.example.mytaskProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNCcil3kyW-PZXJGvPE1YCq4nfEtGlREo',
    appId: '1:240127573028:web:8c58d2cdde5a524df66cb1',
    messagingSenderId: '240127573028',
    projectId: 'ite-e3-todoapp',
    authDomain: 'ite-e3-todoapp.firebaseapp.com',
    storageBucket: 'ite-e3-todoapp.firebasestorage.app',
  );
}
